# Configurações de Conexão com o Banco de Dados MySQL
db.url=jdbc:mysql://localhost:3306/db_recomendador_livros?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
db.user=root
db.password=rootpassword
db.driver=com.mysql.cj.jdbc.Driver
